# Generated by Django 4.0.10 on 2024-11-26 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twit', '0005_alter_twit_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='twit',
            name='image_url',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
